name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Unit tests
      run: ./gradlew test
    - name: Formating ktlint
      run: ./gradlew ktlintFormat
    - name: Code Quality ktlint
      run: ./gradlew ktlint
    - name: Code Quality DeteKT
      run: ./gradlew detekt
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        ndk: 21.0.6113669
        cmake: 3.10.2.4988404
        script: ./gradlew clean jacocoTestReport




